INSERT INTO public.types ("Type", "Supertype") VALUES ('Allium', 'Vegetable');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Berry', 'Fruit');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Citrus', 'Fruit');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Cruciferous', 'Vegetable');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Cucurbit', 'Vegetable');
INSERT INTO public.types ("Type", "Supertype") VALUES ('False Fruit', 'Fruit');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Flower', 'Flower');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Leaf', 'Vegetable');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Legume', 'Vegetable');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Nightshade', 'Vegetable');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Nut', 'Fruit');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Pome Fruit', 'Fruit');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Root', 'Vegetable');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Seed', 'Flower');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Soft Herb', 'Herb');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Stalk', 'Vegetable');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Stone Fruit', 'Fruit');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Vine Fruit', 'Fruit');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Hard Herb', 'Herb');
INSERT INTO public.types ("Type", "Supertype") VALUES ('Woody Herb', 'Herb');
