INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Almond', 'Nut');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Apple', 'Pome Fruit');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Artichoke', 'Flower');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Aubergine', 'Nightshade');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Basil', 'Soft Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Bean', 'Legume');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Beetroot', 'Root');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Blackberry', 'Berry');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Blueberry', 'Berry');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Broccoli', 'Cruciferous');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Cabbage', 'Cruciferous');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Carrot', 'Root');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Cauliflower', 'Cruciferous');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Celery', 'Stalk');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Chilli', 'Nightshade');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Chive', 'Allium');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Coriander', 'Soft Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Cucumber', 'Cucurbit');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Curry Leaf', 'Woody Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Edible Flower', 'Flower');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Fennel', 'Soft Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Fig', 'False Fruit');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Ginger', 'Root');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Gooseberry', 'Berry');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Granadilla', 'Vine Fruit');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Grape', 'Vine Fruit');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Grapefruit', 'Citrus');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Jerusalem Artichoke', 'Root');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Kale', 'Cruciferous');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Kei Apple', 'Berry');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Leek', 'Allium');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Lemon', 'Citrus');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Lemon Balm', 'Soft Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Lemon Verbena', 'Hard Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Lettuce', 'Leaf');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Lime', 'Citrus');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Marjoram', 'Hard Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Mint', 'Soft Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Mustard Leaf', 'Leaf');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Naartjie', 'Citrus');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Nasturtium', 'Flower');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Onion', 'Allium');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Orange', 'Citrus');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Oregano', 'Woody Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Parsley', 'Soft Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Pea', 'Legume');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Peach', 'Stone Fruit');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Pepper', 'Nightshade');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Plum', 'Stone Fruit');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Pumpkin', 'Cucurbit');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Radish', 'Root');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Rhubarb', 'Stalk');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Rosemary', 'Hard Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Sage', 'Hard Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Sorrel', 'Leaf');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Spinach', 'Leaf');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Squash', 'Cucurbit');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Strawberry', 'Berry');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Sunflower Seed', 'Seed');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Sweet Potato', 'Root');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Thyme', 'Hard Herb');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Tomato', 'Nightshade');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Turmeric', 'Root');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Turnip', 'Root');
INSERT INTO public.subtypes ("Subtype", "Type") VALUES ('Zucchini', 'Cucurbit');
